"""
correction.py

Uses Gemini to generate a corrected medical response based on
the original answer and claim verification results.
"""

import os
import json
import time
from google import genai
from google.genai.errors import ServerError

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

MODEL = "gemini-flash-latest"


def generate_corrected_response(original_answer, verification_results):

    claims_to_correct = []

    for item in verification_results:

        if item["verdict"] != "Supported":

            claims_to_correct.append({
                "claim": item["claim"],
                "verdict": item["verdict"],
                "confidence": round(item["confidence"] * 100, 2),
                "evidence": item["evidence"]
            })

    # Everything verified
    if not claims_to_correct:
        return {
            "corrected_response": original_answer,
            "corrected_claims": []
        }

    prompt = f"""
You are a medical fact-correction assistant.

Below is the ORIGINAL RESPONSE generated by an LLM.

-----------------------------
{original_answer}
-----------------------------

Some claims were NOT verified.

For each claim, use ONLY the supplied evidence.

Claims requiring correction:

{json.dumps(claims_to_correct, indent=2)}

Instructions:

1. Keep all VERIFIED information unchanged.
2. Rewrite ONLY unsupported or contradicted claims.
3. Use ONLY the provided evidence.
4. Do not invent facts.
5. Produce a medically accurate final response.
6. Maintain natural flow.
7. Return ONLY the corrected response.
"""

    MAX_RETRIES = 3

    for attempt in range(MAX_RETRIES):

        try:

            response = client.models.generate_content(
                model=MODEL,
                contents=prompt
            )

            corrected = response.text.strip()

            return {
                "corrected_response": corrected,
                "corrected_claims": claims_to_correct
            }

        except ServerError:

            print(
                f"Gemini is busy... Retry {attempt + 1}/{MAX_RETRIES}"
            )

            if attempt == MAX_RETRIES - 1:

                return {
                    "corrected_response": original_answer,
                    "corrected_claims": claims_to_correct,
                    "warning": "Gemini correction service is temporarily unavailable."
                }

            time.sleep(2 ** attempt)

        except Exception as e:

            print(e)

            return {
                "corrected_response": original_answer,
                "corrected_claims": claims_to_correct,
                "warning": str(e)
            }