"""
verifier.py

Verifies medical claims using a Natural Language Inference (NLI) model.

Premise   : Retrieved PubMed evidence
Hypothesis: LLM-generated claim
"""

from transformers import pipeline

# Load the NLI model once
classifier = pipeline(
    task="text-classification",
    model="MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli",
    top_k=None
)

# Decision thresholds
SUPPORTED_THRESHOLD = 0.70
CONTRADICTION_THRESHOLD = 0.70


def verify_claim(claim, evidence_chunks):
    """
    Parameters
    ----------
    claim : str
        Claim generated by the LLM.

    evidence_chunks : list
        Top-k retrieved evidence chunks.

    Returns
    -------
    dict
        {
            "verdict": "...",
            "confidence": 0.95,
            "document_id": "...",
            "chunk_id": 1,
            "evidence": "...",
            "scores": {
                "supported": ...,
                "contradicted": ...,
                "neutral": ...
            }
        }
    """

    best_chunk = None
    best_entailment = -1.0

    for chunk in evidence_chunks:

        try:
            output = classifier(
                {
                    "text": chunk.text,
                    "text_pair": claim
                }
            )

            # Normalize output
            if isinstance(output, dict):
                output = [output]

            if (
                isinstance(output, list)
                and len(output) > 0
                and isinstance(output[0], list)
            ):
                output = output[0]

            scores = {
                "entailment": 0.0,
                "contradiction": 0.0,
                "neutral": 0.0,
            }

            for item in output:
                label = item["label"].lower()

                if label in scores:
                    scores[label] = item["score"]

            # Keep the chunk with highest entailment score
            if scores["entailment"] > best_entailment:

                best_entailment = scores["entailment"]

                best_chunk = {
                    "document_id": chunk.document_id,
                    "chunk_id": chunk.chunk_id,
                    "evidence": chunk.text,
                    "scores": scores
                }

        except Exception as e:
            print(f"Verification Error: {e}")

    # No evidence available
    if best_chunk is None:

        return {
            "verdict": "Not Enough Evidence",
            "confidence": 0.0,
            "document_id": None,
            "chunk_id": None,
            "evidence": "",
            "scores": {
                "supported": 0.0,
                "contradicted": 0.0,
                "neutral": 1.0
            }
        }

    support = best_chunk["scores"]["entailment"]
    contradiction = best_chunk["scores"]["contradiction"]
    neutral = best_chunk["scores"]["neutral"]

    # Final decision
    if support >= SUPPORTED_THRESHOLD:

        verdict = "Supported"
        confidence = support

    elif contradiction >= CONTRADICTION_THRESHOLD:

        verdict = "Contradicted"
        confidence = contradiction

    else:

        verdict = "Not Enough Evidence"
        confidence = neutral

    return {
        "verdict": verdict,
        "confidence": confidence,
        "document_id": best_chunk["document_id"],
        "chunk_id": best_chunk["chunk_id"],
        "evidence": best_chunk["evidence"],
        "scores": {
            "supported": support,
            "contradicted": contradiction,
            "neutral": neutral,
        },
    }